import LovableLogo from "./lovable-logo-bg-light.png";
const Footer = () => {
  return (
    <footer className='bg-orange-100 py-12 mt-12'>
      <div className='container mx-auto px-4 w-1/2'>
        <div className='grid grid-cols-1 md:grid-cols-3 gap-8 mb-8 items-center'>
          {/* TDC Gallery Logo */}
          <div className='text-center'>
            <img
              src='/lovable-uploads/9a3326c1-724d-49fd-8a8e-b2e794a861cd.png'
              alt='TDC Gallery'
              className='h-16 mx-auto mb-2'
            />
          </div>

          {/* Theethawat Logo */}
          <div className='text-center'>
            <img
              src='/lovable-uploads/db4dc714-f7d7-42bf-bf20-37b6560f269d.png'
              alt='Theethawat'
              className='h-16 mx-auto mb-2'
            />
          </div>

          {/* Lovable Logo */}
          <div className='text-center'>
            <img
              src={LovableLogo}
              alt='Lovable AI Coding Agent'
              className='h-6 mx-auto mb-2'
            />
          </div>
        </div>

        {/* Footer Text */}
        <div className='text-center text-orange-700'>
          <p className='mb-2'>
            This site is structured and generated by{" "}
            <a
              href='https://lovable.dev/'
              className='font-semibold hover:text-orange-800 transition-colors'
              target='_blank'
              rel='noopener noreferrer'
            >
              Lovable AI Coding Agent
            </a>
            , content adjust by{" "}
            <a
              href='https://theethawat.dev'
              className='font-semibold hover:text-orange-800 transition-colors'
              target='_blank'
              rel='noopener noreferrer'
            >
              Tin
            </a>{" "}
            and{" "}
            <a
              href='https://theduckcreator.in.th'
              className='font-semibold hover:text-orange-800 transition-colors'
              target='_blank'
              rel='noopener noreferrer'
            >
              TDC
            </a>
          </p>
          <p className='text-orange-600'>Deploy on Azure Static Site</p>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
